In [2]:
%pwd
from sklearn.datasets import make_blobs
import keras
from IPython.display import clear_output
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras import optimizers
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import StratifiedKFold
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.svm import SVC 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB
from sklearn.ensemble import VotingClassifier
from keras.regularizers import l2
from numpy import mean
from numpy import std
from numpy import array
from numpy import argmax
#from keras.utils import to_categorical
from sklearn.metrics import confusion_matrix
import itertools
import pickle
import matplotlib.pyplot as plt
from keras.utils import to_categorical
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import roc_auc_score
from matplotlib import pyplot
from sklearn.metrics import roc_curve, auc
from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle
from keras.callbacks import EarlyStopping
from keras.callbacks import ModelCheckpoint
from keras.models import load_model
from sklearn.model_selection import KFold
#Random Number
r = 42

/Users/manashsarma/opt/anaconda3/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [3]:
GSE63060_geneExpression_csv_df = pd.read_csv('./GSE63060_geneExpression.csv')

/var/folders/bq/sdm0wvbs55vgz21fqdplwghm0000gn/T/ipykernel_44042/124991696.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  GSE63060_geneExpression_csv_df = pd.read_csv('./GSE63060_geneExpression.csv')

In [4]:
GSE63060_geneExpression_df=GSE63060_geneExpression_csv_df.drop(['Symbol','Transcript','Entrez_Gene_ID',
                                                                'Chromosome','Cytoband'], axis = 1)
GSE63060_geneExpression_df.head()

,ILMN_Gene,GSM1539080,GSM1539081,GSM1539082,GSM1539083,GSM1539084,GSM1539085,GSM1539086,GSM1539087,GSM1539088,...,GSM1539399,GSM1539400,GSM1539401,GSM1539402,GSM1539403,GSM1539404,GSM1539405,GSM1539406,GSM1539407,GSM1539408
0,EEF1A1,14.611769,14.427104,14.624553,14.442078,14.127102,14.412088,14.569419,14.624553,14.655069,...,14.668559,14.526182,14.695354,15.049790,14.025296,14.915290,14.655069,14.869782,14.249922,14.891158
1,GAPDH,11.944514,11.930664,11.777748,12.420057,11.725034,11.941696,11.944514,12.608218,12.266326,...,12.126935,11.892791,12.043099,12.019189,12.049508,12.104508,11.903194,11.560549,11.625297,12.064573
2,SLC35E2,7.517737,7.546532,7.647790,7.745140,7.520212,7.716517,7.480014,7.598107,7.815103,...,7.607597,7.622884,7.635975,7.699531,7.649240,7.636703,7.605595,7.581313,7.587167,7.614630
3,LOC642820,7.419066,7.403191,7.382467,7.438868,7.430150,7.441058,7.386403,7.476285,7.422640,...,7.419287,7.395029,7.404132,7.455708,7.435492,7.462115,7.498538,7.470538,7.511239,7.509601
4,RPS28,11.507170,10.506885,12.058497,10.649464,11.958259,10.947954,10.669642,9.963996,10.862309,...,11.016573,11.178761,10.796267,10.828405,10.375336,10.188892,11.489647,11.358234,10.361057,10.521751

In [5]:
GSE63060_geneExpression_df.T.head()

,0,1,2,3,4,5,6,7,8,9,...,38313,38314,38315,38316,38317,38318,38319,38320,38321,38322
ILMN_Gene,EEF1A1,GAPDH,SLC35E2,LOC642820,RPS28,IPO13,LOC653113,AFAP1,GGTLC1,CDT1,...,RPS29,WSB1,WWOX,CD96,SPECC1,DNAJB14,ENOX2,THOC3,MRRF,KIAA1751
GSM1539080,14.611769,11.944514,7.517737,7.419066,11.50717,7.874504,7.516737,7.47973,7.533225,7.341821,...,8.002433,8.847614,7.643837,9.153117,7.473388,8.117209,7.647265,7.898277,8.130117,9.720152
GSM1539081,14.427104,11.930664,7.546532,7.403191,10.506885,8.223289,7.50866,7.413355,7.49376,7.387509,...,8.068787,9.183378,7.62282,9.607767,7.506813,7.832658,7.662759,8.00487,8.129346,10.154313
GSM1539082,14.624553,11.777748,7.64779,7.382467,12.058497,8.160895,7.409548,7.435603,7.488856,7.424961,...,8.012494,8.71207,7.616942,9.717052,7.470607,8.120496,7.750023,8.013598,8.162503,10.733743
GSM1539083,14.442078,12.420057,7.74514,7.438868,10.649464,7.971988,7.669356,7.454023,7.525875,7.499292,...,7.568086,8.679349,7.817522,10.122677,7.493526,7.858918,7.865257,8.255417,8.17903,9.928934

In [6]:
GSE63060_geneExpression_df.head()

,ILMN_Gene,GSM1539080,GSM1539081,GSM1539082,GSM1539083,GSM1539084,GSM1539085,GSM1539086,GSM1539087,GSM1539088,...,GSM1539399,GSM1539400,GSM1539401,GSM1539402,GSM1539403,GSM1539404,GSM1539405,GSM1539406,GSM1539407,GSM1539408
0,EEF1A1,14.611769,14.427104,14.624553,14.442078,14.127102,14.412088,14.569419,14.624553,14.655069,...,14.668559,14.526182,14.695354,15.049790,14.025296,14.915290,14.655069,14.869782,14.249922,14.891158
1,GAPDH,11.944514,11.930664,11.777748,12.420057,11.725034,11.941696,11.944514,12.608218,12.266326,...,12.126935,11.892791,12.043099,12.019189,12.049508,12.104508,11.903194,11.560549,11.625297,12.064573
2,SLC35E2,7.517737,7.546532,7.647790,7.745140,7.520212,7.716517,7.480014,7.598107,7.815103,...,7.607597,7.622884,7.635975,7.699531,7.649240,7.636703,7.605595,7.581313,7.587167,7.614630
3,LOC642820,7.419066,7.403191,7.382467,7.438868,7.430150,7.441058,7.386403,7.476285,7.422640,...,7.419287,7.395029,7.404132,7.455708,7.435492,7.462115,7.498538,7.470538,7.511239,7.509601
4,RPS28,11.507170,10.506885,12.058497,10.649464,11.958259,10.947954,10.669642,9.963996,10.862309,...,11.016573,11.178761,10.796267,10.828405,10.375336,10.188892,11.489647,11.358234,10.361057,10.521751

In [7]:
GSE63060_geneExpression_df.columns

Index(['ILMN_Gene', 'GSM1539080', 'GSM1539081', 'GSM1539082', 'GSM1539083',
       'GSM1539084', 'GSM1539085', 'GSM1539086', 'GSM1539087', 'GSM1539088',
       ...
       'GSM1539399', 'GSM1539400', 'GSM1539401', 'GSM1539402', 'GSM1539403',
       'GSM1539404', 'GSM1539405', 'GSM1539406', 'GSM1539407', 'GSM1539408'],
      dtype='object', length=330)

In [8]:
GSE63060_geneExpression_df.index

RangeIndex(start=0, stop=38323, step=1)

In [9]:
GSE63060_geneExpression_df = GSE63060_geneExpression_df.set_index(['ILMN_Gene'])

In [10]:
GSE63060_geneExpression_df.head()

,GSM1539080,GSM1539081,GSM1539082,GSM1539083,GSM1539084,GSM1539085,GSM1539086,GSM1539087,GSM1539088,GSM1539089,...,GSM1539399,GSM1539400,GSM1539401,GSM1539402,GSM1539403,GSM1539404,GSM1539405,GSM1539406,GSM1539407,GSM1539408
ILMN_Gene,,,,,,,,,,,,,,,,,,,,,
EEF1A1,14.611769,14.427104,14.624553,14.442078,14.127102,14.412088,14.569419,14.624553,14.655069,14.471184,...,14.668559,14.526182,14.695354,15.049790,14.025296,14.915290,14.655069,14.869782,14.249922,14.891158
GAPDH,11.944514,11.930664,11.777748,12.420057,11.725034,11.941696,11.944514,12.608218,12.266326,11.806609,...,12.126935,11.892791,12.043099,12.019189,12.049508,12.104508,11.903194,11.560549,11.625297,12.064573
SLC35E2,7.517737,7.546532,7.647790,7.745140,7.520212,7.716517,7.480014,7.598107,7.815103,7.569682,...,7.607597,7.622884,7.635975,7.699531,7.649240,7.636703,7.605595,7.581313,7.587167,7.614630
LOC642820,7.419066,7.403191,7.382467,7.438868,7.430150,7.441058,7.386403,7.476285,7.422640,7.392535,...,7.419287,7.395029,7.404132,7.455708,7.435492,7.462115,7.498538,7.470538,7.511239,7.509601
RPS28,11.507170,10.506885,12.058497,10.649464,11.958259,10.947954,10.669642,9.963996,10.862309,11.358234,...,11.016573,11.178761,10.796267,10.828405,10.375336,10.188892,11.489647,11.358234,10.361057,10.521751

In [11]:
GSE63060_geneExpression_df.T.head()

ILMN_Gene,EEF1A1,GAPDH,SLC35E2,LOC642820,RPS28,IPO13,LOC653113,AFAP1,GGTLC1,CDT1,...,RPS29,WSB1,WWOX,CD96,SPECC1,DNAJB14,ENOX2,THOC3,MRRF,KIAA1751
GSM1539080,14.611769,11.944514,7.517737,7.419066,11.507170,7.874504,7.516737,7.479730,7.533225,7.341821,...,8.002433,8.847614,7.643837,9.153117,7.473388,8.117209,7.647265,7.898277,8.130117,9.720152
GSM1539081,14.427104,11.930664,7.546532,7.403191,10.506885,8.223289,7.508660,7.413355,7.493760,7.387509,...,8.068787,9.183378,7.622820,9.607767,7.506813,7.832658,7.662759,8.004870,8.129346,10.154313
GSM1539082,14.624553,11.777748,7.647790,7.382467,12.058497,8.160895,7.409548,7.435603,7.488856,7.424961,...,8.012494,8.712070,7.616942,9.717052,7.470607,8.120496,7.750023,8.013598,8.162503,10.733743
GSM1539083,14.442078,12.420057,7.745140,7.438868,10.649464,7.971988,7.669356,7.454023,7.525875,7.499292,...,7.568086,8.679349,7.817522,10.122677,7.493526,7.858918,7.865257,8.255417,8.179030,9.928934
GSM1539084,14.127102,11.725034,7.520212,7.430150,11.958259,8.083689,7.415442,7.449985,7.481328,7.360363,...,7.524517,8.771178,7.484436,9.232231,7.418081,7.849282,7.695439,7.976534,8.083838,10.261227

In [12]:
GSE63060_geneExpression_df.T.columns

Index(['EEF1A1', 'GAPDH', 'SLC35E2', 'LOC642820', 'RPS28', 'IPO13',
       'LOC653113', 'AFAP1', 'GGTLC1', 'CDT1',
       ...
       'RPS29', 'WSB1', 'WWOX', 'CD96', 'SPECC1', 'DNAJB14', 'ENOX2', 'THOC3',
       'MRRF', 'KIAA1751'],
      dtype='object', name='ILMN_Gene', length=38323)

In [13]:
GSE63060_geneExpression_df.T.index

Index(['GSM1539080', 'GSM1539081', 'GSM1539082', 'GSM1539083', 'GSM1539084',
       'GSM1539085', 'GSM1539086', 'GSM1539087', 'GSM1539088', 'GSM1539089',
       ...
       'GSM1539399', 'GSM1539400', 'GSM1539401', 'GSM1539402', 'GSM1539403',
       'GSM1539404', 'GSM1539405', 'GSM1539406', 'GSM1539407', 'GSM1539408'],
      dtype='object', length=329)

In [14]:
GSE63060_geneExpression_df=GSE63060_geneExpression_df.T

In [15]:
GSE63060_geneExpression_df.head()

ILMN_Gene,EEF1A1,GAPDH,SLC35E2,LOC642820,RPS28,IPO13,LOC653113,AFAP1,GGTLC1,CDT1,...,RPS29,WSB1,WWOX,CD96,SPECC1,DNAJB14,ENOX2,THOC3,MRRF,KIAA1751
GSM1539080,14.611769,11.944514,7.517737,7.419066,11.507170,7.874504,7.516737,7.479730,7.533225,7.341821,...,8.002433,8.847614,7.643837,9.153117,7.473388,8.117209,7.647265,7.898277,8.130117,9.720152
GSM1539081,14.427104,11.930664,7.546532,7.403191,10.506885,8.223289,7.508660,7.413355,7.493760,7.387509,...,8.068787,9.183378,7.622820,9.607767,7.506813,7.832658,7.662759,8.004870,8.129346,10.154313
GSM1539082,14.624553,11.777748,7.647790,7.382467,12.058497,8.160895,7.409548,7.435603,7.488856,7.424961,...,8.012494,8.712070,7.616942,9.717052,7.470607,8.120496,7.750023,8.013598,8.162503,10.733743
GSM1539083,14.442078,12.420057,7.745140,7.438868,10.649464,7.971988,7.669356,7.454023,7.525875,7.499292,...,7.568086,8.679349,7.817522,10.122677,7.493526,7.858918,7.865257,8.255417,8.179030,9.928934
GSM1539084,14.127102,11.725034,7.520212,7.430150,11.958259,8.083689,7.415442,7.449985,7.481328,7.360363,...,7.524517,8.771178,7.484436,9.232231,7.418081,7.849282,7.695439,7.976534,8.083838,10.261227

In [16]:
GSE63060_geneExpression_df.shape

(329, 38323)

In [17]:
GSE63060_geneExpression_df.columns

Index(['EEF1A1', 'GAPDH', 'SLC35E2', 'LOC642820', 'RPS28', 'IPO13',
       'LOC653113', 'AFAP1', 'GGTLC1', 'CDT1',
       ...
       'RPS29', 'WSB1', 'WWOX', 'CD96', 'SPECC1', 'DNAJB14', 'ENOX2', 'THOC3',
       'MRRF', 'KIAA1751'],
      dtype='object', name='ILMN_Gene', length=38323)

In [18]:
GSE63060_geneExpression_df.iloc[0]

ILMN_Gene
EEF1A1       14.611769
GAPDH        11.944514
SLC35E2       7.517737
LOC642820     7.419066
RPS28        11.507170
               ...
DNAJB14       8.117209
ENOX2         7.647265
THOC3         7.898277
MRRF          8.130117
KIAA1751      9.720152
Name: GSM1539080, Length: 38323, dtype: float64

In [21]:
GSE63060_samples_df = pd.read_csv('./samples_gse_63060.csv')

In [22]:
GSE63060_samples_df.head()

  geo_accession  age:ch1 gender:ch1 status:ch1
0    GSM1539080       65     Female        MCI
1    GSM1539081       66     Female        MCI
2    GSM1539082       67     Female        MCI
3    GSM1539083       67     Female        MCI
4    GSM1539084       67     Female        MCI

In [23]:
GSE63060_samples_df['status:ch1'].value_counts()

AD     145
CTL    104
MCI     80
Name: status:ch1, dtype: int64

In [24]:
GSE63060_samples_df.shape

(329, 4)

In [32]:
#GSE63060_geneExpression_df.reset_index(inplace=True) -- alreday done , so commented
GSE63060_geneExpression_df['index'].head(5)

0    GSM1539080
1    GSM1539081
2    GSM1539082
3    GSM1539083
4    GSM1539084
Name: index, dtype: object

In [34]:
#df.rename(columns = {'index':'PTID'}, inplace = True)
GSE63060_samples_df.rename(columns = {'geo_accession':'index'}, inplace = True)
GSE63060_samples_df.head(1)

        index  age:ch1 gender:ch1 status:ch1
0  GSM1539080       65     Female        MCI

In [35]:
GSE63060_geneExpression_df=GSE63060_geneExpression_df.merge(GSE63060_samples_df, on=['index'])

In [36]:
GSE63060_geneExpression_df.head(5)

,level_0,index,EEF1A1,GAPDH,SLC35E2,LOC642820,RPS28,IPO13,LOC653113,AFAP1,...,CD96,SPECC1,DNAJB14,ENOX2,THOC3,MRRF,KIAA1751,age:ch1,gender:ch1,status:ch1
0,0,GSM1539080,14.611769,11.944514,7.517737,7.419066,11.507170,7.874504,7.516737,7.479730,...,9.153117,7.473388,8.117209,7.647265,7.898277,8.130117,9.720152,65,Female,MCI
1,1,GSM1539081,14.427104,11.930664,7.546532,7.403191,10.506885,8.223289,7.508660,7.413355,...,9.607767,7.506813,7.832658,7.662759,8.004870,8.129346,10.154313,66,Female,MCI
2,2,GSM1539082,14.624553,11.777748,7.647790,7.382467,12.058497,8.160895,7.409548,7.435603,...,9.717052,7.470607,8.120496,7.750023,8.013598,8.162503,10.733743,67,Female,MCI
3,3,GSM1539083,14.442078,12.420057,7.745140,7.438868,10.649464,7.971988,7.669356,7.454023,...,10.122677,7.493526,7.858918,7.865257,8.255417,8.179030,9.928934,67,Female,MCI
4,4,GSM1539084,14.127102,11.725034,7.520212,7.430150,11.958259,8.083689,7.415442,7.449985,...,9.232231,7.418081,7.849282,7.695439,7.976534,8.083838,10.261227,67,Female,MCI

In [192]:
GSE63060_geneExpression_df.head(5)

,index,EEF1A1,GAPDH,SLC35E2,LOC642820,RPS28,IPO13,LOC653113,AFAP1,GGTLC1,...,CD96,SPECC1,DNAJB14,ENOX2,THOC3,MRRF,KIAA1751,age:ch1,gender:ch1,status:ch1
0,GSM1539080,14.611769,11.944514,7.517737,7.419066,11.507170,7.874504,7.516737,7.479730,7.533225,...,9.153117,7.473388,8.117209,7.647265,7.898277,8.130117,9.720152,65,Female,MCI
1,GSM1539081,14.427104,11.930664,7.546532,7.403191,10.506885,8.223289,7.508660,7.413355,7.493760,...,9.607767,7.506813,7.832658,7.662759,8.004870,8.129346,10.154313,66,Female,MCI
2,GSM1539082,14.624553,11.777748,7.647790,7.382467,12.058497,8.160895,7.409548,7.435603,7.488856,...,9.717052,7.470607,8.120496,7.750023,8.013598,8.162503,10.733743,67,Female,MCI
3,GSM1539083,14.442078,12.420057,7.745140,7.438868,10.649464,7.971988,7.669356,7.454023,7.525875,...,10.122677,7.493526,7.858918,7.865257,8.255417,8.179030,9.928934,67,Female,MCI
4,GSM1539084,14.127102,11.725034,7.520212,7.430150,11.958259,8.083689,7.415442,7.449985,7.481328,...,9.232231,7.418081,7.849282,7.695439,7.976534,8.083838,10.261227,67,Female,MCI

In [193]:
GSE63060_geneExpression_df.to_csv('./GSE63060_geneExpression_diagnosis.csv')

In [37]:
GSE63060_geneExpression_df.columns

Index(['level_0', 'index', 'EEF1A1', 'GAPDH', 'SLC35E2', 'LOC642820', 'RPS28',
       'IPO13', 'LOC653113', 'AFAP1',
       ...
       'CD96', 'SPECC1', 'DNAJB14', 'ENOX2', 'THOC3', 'MRRF', 'KIAA1751',
       'age:ch1', 'gender:ch1', 'status:ch1'],
      dtype='object', length=38328)

In [38]:
GSE63060_geneExpression_df.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            319, 320, 321, 322, 323, 324, 325, 326, 327, 328],
           dtype='int64', length=329)

In [42]:
GSE63060_geneExpression_df.drop('level_0',axis =1,inplace=True)

In [43]:
GSE63060_geneExpression_df.head()

,index,EEF1A1,GAPDH,SLC35E2,LOC642820,RPS28,IPO13,LOC653113,AFAP1,GGTLC1,...,CD96,SPECC1,DNAJB14,ENOX2,THOC3,MRRF,KIAA1751,age:ch1,gender:ch1,status:ch1
0,GSM1539080,14.611769,11.944514,7.517737,7.419066,11.507170,7.874504,7.516737,7.479730,7.533225,...,9.153117,7.473388,8.117209,7.647265,7.898277,8.130117,9.720152,65,Female,MCI
1,GSM1539081,14.427104,11.930664,7.546532,7.403191,10.506885,8.223289,7.508660,7.413355,7.493760,...,9.607767,7.506813,7.832658,7.662759,8.004870,8.129346,10.154313,66,Female,MCI
2,GSM1539082,14.624553,11.777748,7.647790,7.382467,12.058497,8.160895,7.409548,7.435603,7.488856,...,9.717052,7.470607,8.120496,7.750023,8.013598,8.162503,10.733743,67,Female,MCI
3,GSM1539083,14.442078,12.420057,7.745140,7.438868,10.649464,7.971988,7.669356,7.454023,7.525875,...,10.122677,7.493526,7.858918,7.865257,8.255417,8.179030,9.928934,67,Female,MCI
4,GSM1539084,14.127102,11.725034,7.520212,7.430150,11.958259,8.083689,7.415442,7.449985,7.481328,...,9.232231,7.418081,7.849282,7.695439,7.976534,8.083838,10.261227,67,Female,MCI

In [44]:
GSE63060_geneExpression_df.to_csv('GSE63060_geneExpression.csv')

In [101]:
GSE63060_geneExpression_df.shape

(329, 38327)

In [110]:
    duplicateColNames = GSE63060_geneExpression_dup_86_df.columns.duplicated()

In [113]:
GSE63060_geneExpression_dup_86_df.columns[duplicateColNames]

Index(['APP', 'APP', 'ARHGAP17', 'ARHGAP17', 'ATP9A', 'ATP9A', 'CCPG1',
       'CDCP1', 'CDCP1', 'EIF1AY', 'ERG', 'ERG', 'FARP1', 'FARP1', 'ICA1L',
       'INTS6', 'MAPK14', 'MAPK14', 'MAPK14', 'MID1', 'MSH3', 'NBPF1', 'NBPF1',
       'NBPF1', 'NR1I2', 'NR1I2', 'PDC', 'PRR15', 'RCN2', 'RPL32', 'RPL32',
       'RPL32', 'SORBS3', 'SQLE', 'STRN', 'OVOS2', 'OVOS2', 'OVOS2',
       'C1ORF187', 'STAG1', 'GPER', 'GPER'],
      dtype='object')

In [122]:
dup_cols_GSE63060 = ['APP', 'APP', 'ARHGAP17', 'ARHGAP17', 'ATP9A', 'ATP9A', 'CCPG1',
       'CDCP1', 'CDCP1', 'EIF1AY', 'ERG', 'ERG', 'FARP1', 'FARP1', 'ICA1L',
       'INTS6', 'MAPK14', 'MAPK14', 'MAPK14', 'MID1', 'MSH3', 'NBPF1', 'NBPF1',
       'NBPF1', 'NR1I2', 'NR1I2', 'PDC', 'PRR15', 'RCN2', 'RPL32', 'RPL32',
       'RPL32', 'SORBS3', 'SQLE', 'STRN', 'OVOS2', 'OVOS2', 'OVOS2',
       'C1ORF187', 'STAG1', 'GPER', 'GPER']

In [123]:
print(list(set(dup_cols_GSE63060)))

['MID1', 'PRR15', 'NBPF1', 'OVOS2', 'PDC', 'NR1I2', 'ERG', 'C1ORF187', 'CDCP1', 'APP', 'EIF1AY', 'RPL32', 'MSH3', 'CCPG1', 'ICA1L', 'INTS6', 'ARHGAP17', 'MAPK14', 'GPER', 'STAG1', 'SQLE', 'ATP9A', 'FARP1', 'RCN2', 'STRN', 'SORBS3']

In [114]:
len(GSE63060_geneExpression_dup_86_df.columns[duplicateColNames])

42

In [124]:
dup_cols_name_GSE63060=list(set(dup_cols_GSE63060))

In [126]:
len(dup_cols_name_GSE63060)

26

In [128]:
GSE63060_geneExpression_dup_86_df['MID1'].head()

       MID1      MID1
0  8.175836  7.497331
1  7.947158  7.406826
2  7.891917  7.432030
3  8.128256  7.512239
4  8.062162  7.560183

In [146]:
GSE63060_geneExpression_dup_86_df['MID1'].median(axis=1)

0      7.836583
1      7.676992
2      7.661973
3      7.820247
4      7.811173
         ...
324    7.726114
325    7.800644
326    7.679106
327    7.773785
328    7.763094
Length: 329, dtype: float64

In [147]:
GSE63060_geneExpression_dup_86_df['MID1']

         MID1      MID1
0    8.175836  7.497331
1    7.947158  7.406826
2    7.891917  7.432030
3    8.128256  7.512239
4    8.062162  7.560183
..        ...       ...
324  8.075118  7.377111
325  8.074598  7.526689
326  7.948988  7.409224
327  8.083689  7.463881
328  8.074598  7.451589

[329 rows x 2 columns]

In [148]:
# First Store
GSE63060_geneExpression_no_dup_86_df = GSE63060_geneExpression_dup_86_df.copy()

In [151]:
# Loop through the columns names that has duplicate
# For each column take median of the column values
# Store as single column median 
# Remove the dumplicate column and add the single column
for i in dup_cols_name_GSE63060:
    #print (i)
    df = GSE63060_geneExpression_no_dup_86_df[i].median(axis=1)
    GSE63060_geneExpression_no_dup_86_df.drop(i, axis =1, inplace = True)
    GSE63060_geneExpression_no_dup_86_df[i] = df

In [152]:
GSE63060_geneExpression_no_dup_86_df.shape

(329, 86)

In [153]:
GSE63060_geneExpression_dup_86_df.shape

(329, 128)

In [154]:
GSE63060_geneExpression_no_dup_86_df.head()

,AIFM2,ARRDC5,B3GALT1,CEP72,DDX6,DEFB128,DMC1,EIF2A,FAM26D,FASTKD5,...,ARHGAP17,MAPK14,GPER,STAG1,SQLE,ATP9A,FARP1,RCN2,STRN,SORBS3
0,7.553374,8.869689,7.636005,7.539159,7.445275,7.503756,11.836902,8.134517,7.450175,8.348931,...,8.004272,7.866960,8.193895,7.699072,7.606210,7.658433,7.481797,7.592426,8.246395,7.807186
1,7.524215,8.264474,7.583262,7.477244,7.699778,7.410866,12.424184,8.135787,7.417966,8.447775,...,8.425994,7.833812,7.639694,7.745247,7.640742,7.669701,7.578948,7.561263,8.226767,7.796658
2,7.502897,8.526944,7.573596,7.515627,7.541115,7.525243,12.566807,8.099981,7.457434,8.341053,...,8.274136,7.805429,7.565812,7.810048,7.622748,7.577011,7.438124,7.658869,7.955036,7.854947
3,7.523307,8.496517,7.712652,7.424585,7.483658,7.461659,12.234680,8.176677,7.489969,8.403636,...,7.936683,7.987256,7.569629,7.720105,7.555355,7.523673,7.468518,7.615130,8.068666,7.887594
4,7.555918,8.667551,7.673636,7.476086,7.455864,7.556252,12.456033,8.024190,7.582233,8.074738,...,8.183483,7.753695,7.563201,7.632483,7.563911,7.598424,7.428996,7.524824,8.372974,7.756886